language: node_js
branches:
  only:
    - "/.*/"
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
  - stage: Test
    script:
    - commitlint-travis
    - yarn test

  - stage: Deploy Site
    script:
      - yarn site.build
      - cd ./packages/site
    deploy:
      skip_cleanup: true
      provider: firebase
      token:
        secure: $FIREBASE_TOKEN

  - stage: Deploy CSS Demo
    script:
      - yarn scss.build
      - cd ./packages/scss
    deploy:
      skip_cleanup: true
      provider: firebase
      token:
        secure: $FIREBASE_TOKEN

  - stage: Deploy Atoms Demo
    script:
      - yarn atoms.build
      - cd ./packages/atoms
    deploy:
      skip_cleanup: true
      provider: firebase
      token:
        secure: $FIREBASE_TOKEN
