name: Test Pull Request

on: [pull_request]

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - uses: wagoid/commitlint-github-action@v1

      - name: Install
        run: npm ci

      - name: Test
        run: npm test
